### PR TITLE
Change Text type to str and fix some inconsistent types

### PR DESCRIPTION
**Pull request by advay168**

### CODE REVIEW

**Comment by SekouDiaoNlp** [comment]
Hi @advay168 , thank you for your PR.
I agree with you for replacing false by an empty set is a good idea.

Good job also splitting the Typing hierarchy.

I will run the test suite and let you know.

I will add you to the collaborators list.

Cheers,

SekouDIaoNLP

**Comment by SekouDiaoNlp** [comment]
Oh btw @advay168 is there some performance reasons to prefer `str` to `Text`?

Are there other circumstances where the converse is true?

**Comment by SekouDiaoNlp** [comment]
Tweaked type annotations.

**Comment by advay168** [comment]
@SekouDiaoNlp
Typing doesn't have any impact on performance as it is ignored at runtime. I replaced `Text` as support for python 2 was dropped and is equivalent to `str` in python 3. 
[](https://docs.python.org/3/library/typing.html#typing.Text)

**Comment by SekouDiaoNlp** [comment]
Hi @advay168 , I am aware that typing doesn't have performance implications on the official CPython implementation, but many Silicon Valley use more and more alternative Python implementations using type annotations to tune their run times. I think Instagram and reddit gave talks about that at last Pay on.

**Comment by advay168** [comment]
I do not believe this change should have any performance impact as both should be interchangeable and `Text` is only needed in python 2. [Reference](https://docs.python.org/3/library/typing.html#typing.Text)

**Review by SekouDiaoNlp — COMMENTED** [review]
LGTM

**Review by SekouDiaoNlp — COMMENTED** [review]
LGTM

**Pull request merged**
